### ISSUE TITLE
Need more info in the docs to run the server

### ISSUE THREAD

**Issue by dhowdy** [lemberg/connfa-integration-server#1]
Hello,

I'm trying to follow the docs for the server located here: http://connfa.com/integration-server/install/ but I'm not getting it to work.  I've got all of the dependencies installed.  However when I run `php artisan serve` get messages such as this:

{"message":"The version given was unknown or has no registered routes.","status_code":400}

Would you possibly be able to provide some deeper documentation than what exists?

Thanks!
Don

**Comment by dhowdy** [comment]
Setting API_PREFIX=api in .env helped fix part of the issue and setting API_VERSION to V2 on line 48 of ./config/api.php seems to have fixed the rest of the problem.  I'm able to get sample data from the DB now.

**Comment by yuriymyrosh** [comment]
@dhowdy you can set API_VERSION=v2 in your .env file also. I will add initial configuration in .env.example file and also I will add info about this in documentation.

**Comment by dhowdy** [comment]
Thank you!
