### ISSUE TITLE
Getting error on composer install --no-dev

### ISSUE THREAD

**Issue by anderick** [lemberg/connfa-integration-server#11]
I'm trying to install the integration server but when I run composer install --no-dev, I get the following message:

 php artisan optimize

  [ReflectionException]
  Class Faker\Generator does not exist

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by yuriymyrosh** [comment]
@anderick thank you for this issue. It is because package "fzaninotto/faker" is included only in dev dependencies in ```composer.json``` but it is used for database seeding (we will fix this in next release). To run application you can change it by yourself or use ```composer install``` instead of ```composer install --no-dev``` for now

**Comment by yuriymyrosh** [comment]
fixed #11 in 1.1.2
