### ISSUE TITLE
Post Installation Server Issues

### ISSUE THREAD

**Issue by nikkieella** [lemberg/connfa-integration-server#12]
Hi so my team is currently trying to use Connfa for our upcoming event. After our installation we ran into an issue trying to get the server to run to check our updates through the CMS.

What is the command to start the API? We tried "php artisan serve". It shows on a local host but how do you make it public or start the server publicly? 

Here is our code:

"PP_ENV=local
APP_DEBUG=true
APP_KEY=base64:W3TeUBt8KWYovatPDP5qwPvzvGnU1xrkewnvvZqxjUA=
APP_URL=http://app.server.tedxucsd.com

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=appbeta
DB_USERNAME= username
DB_PASSWORD= password

CACHE_DRIVER=array
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

API_PREFIX=api
API_DOMAIN=
API_VERSION=v2
API_DEBUG=true
API_CONDITIONAL_REQUEST=false"

Any thoughts?

**Comment by yuriymyrosh** [comment]
@nikkieella hi!

php artisan serve - this command runs local web server you can make the port public but for production it's better to use apache or nginx. You need to configure your web root to /{appath}/public directory.

**Comment by yuriymyrosh** [comment]
@nikkieella Just want to follow up on this, is the problem still relevant, or could the issue be closed? If there are any questions, just let me know.

**Comment by sphephelo** [comment]
Hi @Konro1, I am struggling with the same issue but on the localhost. I have gone through the documentation and cannot seem to get the BASE URL correct so that I have the APP and the INTEGRATION SERVER working. Please assist.

**Comment by sphephelo** [comment]
@Konro1 using your default URL: http://dublin2016.drupalcon.uat.link/api/v2/ ... the APP connects but fails when I try http://localhost/connfa-server/public/api/v2/. The CMS/Integration Server works fine and I have updated the data but I need the two to communicate.
