### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by phls** [lemberg/connfa-integration-server#13]
Hi,
After installed, I can login, put I receive these 3 messages:

ErrorException in 34e4b611ec528e06b78fd64f43c7aa157e4bb0f6.php line 18: getimagesize(http://MY_URL/index.php/uploads/fakers/b7fa5278b160386db95eae190ebef675.jpg): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
(View: /MY_PATH/connfa/resources/views/partials/speaker.blade.php) (View: /srv/connfa.curitibalivre.org.br/www/connfa/resources/views/partials/speaker.blade.php)

ErrorException in 34e4b611ec528e06b78fd64f43c7aa157e4bb0f6.php line 18: getimagesize(http://MY_URL/index.php/uploads/fakers/b7fa5278b160386db95eae190ebef675.jpg): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
(View: /MY_PATH/connfa/resources/views/partials/speaker.blade.php)

ErrorException in 34e4b611ec528e06b78fd64f43c7aa157e4bb0f6.php line 18: getimagesize(http://MY_URL/index.php/uploads/fakers/b7fa5278b160386db95eae190ebef675.jpg): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found

Thanks.

**Comment by yuriymyrosh** [comment]
Hi, @phls 
We found this error to. It appears when images has unreachable link.
We will fix this issue in next release.
For now you can fix it in file resources/views/partials/speaker.blade.php line 14
Instead of code
```
@if(empty($speaker->avatar))
{{ Html::image('/assets/images/user.png', $speaker->fullname, ['width' => 85, 'height' => 85, 'class' => 'img-circle dash-circle-profile-img']) }}
@else
    <?php list($width, $height, $type, $attr) = getimagesize($speaker->avatar);
    $class = '';
    if($width < $height){
        $class = 'dash-circle-profile-img-height';
    }
    ?>
{{ Html::image($speaker->avatar, $speaker->fullname, ['width' => 85, 'height' => 85, 'class' => "img-circle dash-circle-profile-img $class"]) }}
@endif
```
use this

```
 @if(empty($speaker->avatar))
    {{ Html::image('/assets/images/user.png', $speaker->fullname, ['width' => 85, 'height' => 85, 'class' => 'img-circle dash-circle-profile-img']) }}
@else
    <?php
    try {
        list($width, $height, $type, $attr) = getimagesize($speaker->avatar);
        $class = '';

        if ($width < $height) {
            $class = 'dash-circle-profile-img-height';
        }
        $real_image = true;
    } catch (\Exception $e) {
        $real_image = false;
    }
    ?>
    @if ($real_image)
        {{ Html::image($speaker->avatar, $speaker->fullname, ['width' => 85, 'height' => 85, 'class' => "img-circle dash-circle-profile-img $class"]) }}
    @else
        {{ Html::image('/assets/images/user.png', $speaker->fullname, ['width' => 85, 'height' => 85, 'class' => 'img-circle dash-circle-profile-img']) }}
    @endif
@endif
```

**Comment by phls** [comment]
Done. Thanks.
