### ISSUE TITLE
Installation guide needs to be adjusted

### ISSUE THREAD

**Issue by karmakoff** [lemberg/connfa-integration-server#15]
During the installation some steps did not work properly.

1. Composer did not have the _predis/predis_
    Cured by: **composer require predis/predis**

2. There was no default admin user.
     Had to create some workaround to create admin user and after that change the password using the console command

**Comment by yuriymyrosh** [comment]
@karmakoff thank you for your feedback.

1. Redis is not required for Connfa app. If you want to use it you can add predis/predis package. 
2. To seed admin user you can run ```php artisan db:seed --class=UsersTableSeeder```. We will add this to our documentation.

**Comment by vpauk** [comment]
We updated documentation http://connfa.com/integration-server/install/ 

In case of any questions or issues, just let us know.
