### ISSUE TITLE
404 to my website, please help

### ISSUE THREAD

**Issue by kenyiu6** [lemberg/connfa-integration-server#18]
The solution is changed the AllowOverride to All

**Comment by kenyiu6** [comment]
I have changed the DocumentRoot, but still not working.
![httpd](https://cloud.githubusercontent.com/assets/28314307/25654212/d0c087d8-3022-11e7-9a16-2ea2bb588404.jpg)

**Comment by kenyiu6** [comment]
I have changed the document root to /var/www/html/connfa-integration-server.
You can see the page is okay. http://13.228.27.99/
But there is an 404 error for http://13.228.27.99/login

**Comment by vpauk** [comment]
@kenyiu6 

Could you change DocumentRoot to `/var/www/html/integration-server/public `

Comment following section:
```
<Directory "/var/www">
	# Ignore the .htaccess file in this directory
	AllowOverride None
	# Allow open access
	Requiere all granted		
</Directory>
```


and after that restart web server

**Comment by kenyiu6** [comment]
It works now. Thank you!
