### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by Nataliya-Kulinenko** [lemberg/connfa-integration-server#2]
Content Management System

**Comment by vipulpurohit** [comment]
Thanks for this great application.
I'm a newbie in PHP, I've done the server setup according to connfa documentation and the APIs are working fine.
Now i need update conference details. I'm not able to find any content managment system or any admin panel to feed data for the application. How can I feed my conference details in database so application can access it?
Am I missing something? Can you please help in this issue?

**Comment by Nataliya-Kulinenko** [comment]
Hi @vipulpurohit, new version of Integration Server with CMS is available on GitHub.
You can also find all the details on installation/configuration in Connfa Documentation: http://connfa.com/documentation/
