### ISSUE TITLE
Problem with editing

### ISSUE THREAD

**Issue by izanie** [lemberg/connfa-integration-server#20]
In my instalation some of the addresses do not work. Foe example I can add session, keynote speaker or anything else, but when click view or edit for this item I receive error 404.

Example: 
- [site]/[conference]//sessions/76/edit
- [site]/[conference]//sessions/76

Other addresses are ok (eg I can see the lists of sessions, speakers etc.)

Do you have any idea of what shall I reconfigure? check? change?

**Comment by vpauk** [comment]
@izanie 

Could you provide an example of your site url. For example http://{domain.example}/conference/{conference_alias}/sessions/76/edit

And could you provide DocumentRoot of web server where your installed application ?

**Comment by coldmachine** [comment]
Facing the same problem. Cannot edit/view/delete events and speakers.
MySite urls:

http://connfa.mysite.com/connfalias/bofs/53
http://connfa.mysite.com/connfalias/speakers/52

Also the uploaded images are not showing up.

**Comment by vpauk** [comment]
@coldmachine 

Could you provide more info about problem, for example screenshot of page or error code and error description ?

And could you provide DocumentRoot of web server where your installed application ?

**Comment by coldmachine** [comment]
I am getting 404 error for all of them. The screen shot for the error is [404 error](http://imgur.com/a/GK47W)

I am getting error in both local machine and shared host.
Also my Laravel version is : Laravel Framework version 5.2.32

**Comment by vpauk** [comment]
@coldmachine 

Could you provide DocumentRoot  (or virtualhost configs) of web server where your application installed ?

**Comment by coldmachine** [comment]
@vpauk 
Does it matter?
My Other Laravel applications are running smoothly both on local machine and shared host.

For this project
I changed the db from MySQL to SQLite. Also in .env file I changed
 CACHE_DIRECTORY = array

The problem are view/edit/delete of events/speakers(404 error). I can view the list of events/speakers but can not view detail,edit or delete them. Also in another thread I have reported that the command
$php artisan route:list
 shows error

If you want to check I can upload the whole project here. 

Thanks

**Comment by vpauk** [comment]
@coldmachine 

Is your DocumentRoot path configured to folder "public" and are you enabled mod_rewrite in apache ?

**Comment by coldmachine** [comment]
@vpauk 
I am using mac.
According to my understanding,  the DocumentRoot path is in public folder(i.e. /Library/WebServer/Documents) and mod_rewrite in apache is enabled i.e. 
The /etc/apache2/httpd.conf file has

LoadModule rewrite_module libexec/apache2/mod_rewrite.so

The problem with this project is that I can add new items but cannot view detail, edit or delete.

**Comment by vpauk** [comment]
@coldmachine 

We have tested project in local machine and server everything is working.
About `DocumentRoot`, is your `DocumentRoot` have path to "public" folder ? "public" folder it is Laravel default public folder where is index.php and it is entry point.

Config Document root have to have path to Laravel "public" folder, something like this` DocumentRoot /var/www/public` - where "public" it is Laravel folder

**Comment by coldmachine** [comment]
@vpauk 
I think this has nothing to do with the DocumentRoot because all other functions like listing and adding new items(like speakers, events) are working perfectly.

I was using SQLite. Now I changed the database from SQLite to MySQL and now all functions are working without any problem. So my guess is that there may be issues due to SQLite. 
Many thanks for the suggestions.

**Comment by vpauk** [comment]
@coldmachine 

In case of any questions or issues, just let us know.

**Comment by juniorcesar** [comment]
I am having the same problem, I use the mysql and my apache conf is: 
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html/public
	
 <Directory /var/www/html/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>


Somebody could help me?

**Comment by coldmachine** [comment]
@juniorcesar 
I found the problem is not in configuration but in code. 
I changed the  function checkConference($id) in app/Http/CMS/BaseController.php to following. The old code is commented.


   /**
     *
     * Check if item belong to conference
     *
     * @param integer $id
     * @throws NotFoundHttpException
     */
    protected function checkConference($id)
    {
        Log::info('conference id: '.$this->getConference()->id);
        Log::info('passed id :'.$id);
/*
        if (!$this->getConference() || $id !== $this->getConference()->id) {
            Log::info('Conference not found');
            throw new NotFoundHttpException();
        }
*/
        if (!$this->getConference()) {
            Log::info('Conference not found');
            throw new NotFoundHttpException();
        }else if ($id != $this->getConference()->id){
            Log::info('Conference not found');
            throw new NotFoundHttpException();
        }
    }

**Comment by SagarKapasi099** [comment]
I Am Also Facing This Issue.
the editing, deleting and viewing (for example: speakers) is not working and it is showing 404 error.
but the deleting/ editing/ viewing conferences are working.

i configured the local server (in wampp) the same way as i did the production server. local server is working fine.

here are my configuration.

> index.php

public folder contents are in server/public_html
private folder contents are in server/private_html

`require __DIR__.'/../private_html/bootstrap/autoload.php';
$app = require_once __DIR__.'/../private_html/bootstrap/app.php';
`

> .env

```
APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:generated_by_php_artisan_key:generate
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=correct_database
DB_USERNAME=correct_username
DB_PASSWORD=correct_password

CACHE_DRIVER=array
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

API_PREFIX=api
API_DOMAIN=
API_VERSION=v2
API_DEBUG=true
API_CONDITIONAL_REQUEST=false

APP_LINK_GOOGLE_PLAY=1
APP_LINK_APPLE_STORE=2

CACHE_DIRECTORY=array

```


```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>
    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

<IfModule mod_headers.c>
    <FilesMatch "(?i)\.(ico|jpg|jpeg|png|gif)$">
        Header set Cache-Control "max-age=172800, public, must-revalidate"
    </FilesMatch>
</IfModule>
```


Please Suggest what is wrong with my setup/ how should i reconfigure.

**Comment by SagarKapasi099** [comment]
> @vpauk
> I think this has nothing to do with the DocumentRoot because all other functions like listing and adding new items(like speakers, events) are working perfectly.
> 
> I was using SQLite. Now I changed the database from SQLite to MySQL and now all functions are working without any problem. So my guess is that there may be issues due to SQLite.
> Many thanks for the suggestions.

Were You Able To Solve This Issue?

**Comment by SagarKapasi099** [comment]
> I Am Also Facing This Issue.
> the editing, deleting and viewing (for example: speakers) is not working and it is showing 404 error.
> but the deleting/ editing/ viewing conferences are working.
> 
> i configured the local server (in wampp) the same way as i did the production server. local server is working fine.
> 
> here are my configuration.
> 
> > index.php
> 
> public folder contents are in server/public_html
> private folder contents are in server/private_html
> 
> `require __DIR__.'/../private_html/bootstrap/autoload.php'; $app = require_once __DIR__.'/../private_html/bootstrap/app.php'; `
> 
> > .env
> 
> ```
> APP_ENV=local
> APP_DEBUG=true
> APP_KEY=base64:generated_by_php_artisan_key:generate
> APP_URL=http://localhost
> 
> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
> DB_DATABASE=correct_database
> DB_USERNAME=correct_username
> DB_PASSWORD=correct_password
> 
> CACHE_DRIVER=array
> SESSION_DRIVER=file
> QUEUE_DRIVER=sync
> 
> REDIS_HOST=127.0.0.1
> REDIS_PASSWORD=null
> REDIS_PORT=6379
> 
> MAIL_DRIVER=smtp
> MAIL_HOST=mailtrap.io
> MAIL_PORT=2525
> MAIL_USERNAME=null
> MAIL_PASSWORD=null
> MAIL_ENCRYPTION=null
> 
> API_PREFIX=api
> API_DOMAIN=
> API_VERSION=v2
> API_DEBUG=true
> API_CONDITIONAL_REQUEST=false
> 
> APP_LINK_GOOGLE_PLAY=1
> APP_LINK_APPLE_STORE=2
> 
> CACHE_DIRECTORY=array
> ```
> 
> ```
> <IfModule mod_rewrite.c>
>     <IfModule mod_negotiation.c>
>         Options -MultiViews
>     </IfModule>
>     RewriteEngine On
> 
>     # Redirect Trailing Slashes If Not A Folder...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteRule ^(.*)/$ /$1 [L,R=301]
> 
>     # Handle Front Controller...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^ index.php [L]
> 
>     # Handle Authorization Header
>     RewriteCond %{HTTP:Authorization} .
>     RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
> </IfModule>
> 
> <IfModule mod_headers.c>
>     <FilesMatch "(?i)\.(ico|jpg|jpeg|png|gif)$">
>         Header set Cache-Control "max-age=172800, public, must-revalidate"
>     </FilesMatch>
> </IfModule>
> ```
> 
> Please Suggest what is wrong with my setup/ how should i reconfigure.

Fixed It By Removing  `|| $id !== $this->getConference()->id ` from the if statement in function checkConference($id) in app/Http/CMS/BaseController.php
