### ISSUE TITLE
Missing login URL

### ISSUE THREAD

**Issue by alexanderbenavidez** [lemberg/connfa-integration-server#21]
Hi. I seem to be getting an error - The requested URL /login was not found on this server.

Did I miss to install something?

Thanks!

**Comment by alexanderbenavidez** [comment]
Please disregard. This is now ok. Thanks!

**Comment by wuiler** [comment]
How you solve @alexanderbenavidez  The requested URL /login was not found on this server.

**Comment by alexanderbenavidez** [comment]
Hi Jose,

Don't forget to change ownership of the document root folder. This solved
it for me.

sudo chown -R www-data /path/to/documentroot

This is if you are using Ubuntu Linux.


Regards,

Alex


On Mon, Jul 10, 2017 at 8:19 PM, Jose Wuiler Pozzi <notifications@github.com
