### ISSUE TITLE
How to create new user

### ISSUE THREAD

**Issue by nedasvi** [lemberg/connfa-integration-server#22]
Hello, I seeded the admin user and everything works well, but I need to make additional users for my team members. How can I do that, because I don't see any options in the CMS itself. Thanks!

**Comment by vpauk** [comment]
@Chiuvitas 

You can add additional users from page /users

![f0utzltkrwwxg7o0rejadq](https://user-images.githubusercontent.com/1300584/27956243-8d73ff5a-6321-11e7-87aa-8f10138ee34f.png)

Documentation -> http://connfa.com/integration-server/cms/ -> Users

**Comment by nedasvi** [comment]
There is no Users button
![image](https://user-images.githubusercontent.com/9870765/28115160-85aa5014-670c-11e7-98b9-6557701cae3e.png)

**Comment by vpauk** [comment]
@Chiuvitas 

Maybe your user does not have admin permissions, because only admin has permission to see page /users.

I suggest to remove data from database and seed database again. For this you should run following commands:

1. `php artisan migrate:refresh`
2. `php artisan db:seed`
3. `php artisan password:change --name=admin --password=YOUR_PASSWORD_HERE`

**Comment by halburgiss** [comment]
I have the very same issue. Running your suggested commands does not solve the issue, and results in errors like ...

[Illuminate\Database\QueryException]                                                                                                            
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQL: insert into `event_levels` (`id`, `name`, `c  
  onference_id`, `updated_at`, `created_at`) values (1, Beginner, 1, 2019-03-20 12:53:39, 2019-03-20 12:53:39))                         

In the Roles table: "User is allowed to manage and edit other users"

**Comment by yuriymyrosh** [comment]
@halburgiss Hi, you should use unique id or leave it empty when you are inserting new level (MySQL will auto increment id for you)

**Comment by halburgiss** [comment]
I am not inserting anything. I was running the commands mentioned above:

php artisan migrate:refresh
php artisan db:seed

I resolved the issue by starting over with clean db. On the initial install I did not run the 'db:seed' as it sounded optional. I ran it the second time around. So it seems it is a required step.
