### ISSUE TITLE
Application in Production

### ISSUE THREAD

**Issue by Jazz527** [lemberg/connfa-integration-server#28]
Greetings!

I'm having an issue setting up the server. Whenever I run 

php artisan migrate

It gives me "Application In Production! Do you really wish to run this command? (Y/N)"

When I respond with yes I get the following error:

[PDOException]
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

I'm not sure what I need to do or if I have done anything wrong.

Thanks

**Comment by Jazz527** [comment]
Never mind. I was able to figure out the problem. Mysql server kept closing and failing which messed up the connection. Thanks

**Comment by yuriymyrosh** [comment]
Hi @Jazz527 !
It looks like you have some problem with MySQL or with connection configuration.
Connection configurations you can manage in `.env` file.
Also you can check our requirements for web server and mysql here http://connfa.com/integration-server/server-requirements/

**Comment by Jazz527** [comment]
Thank you so much for the help. I will be posting a separate issue on a new thread. 

Thanks again for the help. I'm very new to this!
