### ISSUE TITLE
Wrong url for the avatar in the speakers index

### ISSUE THREAD

**Issue by jdenisgiguere** [lemberg/connfa-integration-server#29]
Current situation
====

When I upload the picture of a speaker, the avatar in the speakers page is not found.

![broken_avantar](https://user-images.githubusercontent.com/973241/31381551-e286e268-ad82-11e7-9abb-94ce06b0319d.png)

Please note that the upload is sucessful and the picture is visible in other contexts.

Expected situation
===

As smaller version of the picture should appears in the circle at the right of the speaker number.

Setup information
===

I'm using connfa-integration-server commit 9dbd0435109b3a0a6254387faf23123a79d275d8 .
PHP  7.0.22-0ubuntu0.17.04.1.
Ubuntu Zesty.

**Comment by jdenisgiguere** [comment]
It looks like the url is not complete.

Connfa is installed with the url prefix cms, but the prefix does not appear in the generated image source.

**Example**

The image source is : 

 /uploads/speakers/2017-10-10-09-49-03-20728037-789676387876894-1291252172571061685-n.jpg
But the image is available at:

 /prefix/uploads/speakers/2017-10-10-09-49-03-20728037-789676387876894-1291252172571061685-n.jpg

Adding manually the prefix makes the image reachable.

**Comment by yuriymyrosh** [comment]
@jdenisgiguere it looks like you need to add your domain in .env `APP_URL=YOUR_DOMAIN_HERE`

**Comment by jdenisgiguere** [comment]
Thank you!

I  was using my own Apache rewrite Rules which is not okay for static files. I will use the APP_URL parameter in future.
