### ISSUE TITLE
install not working from fresh webserver

### ISSUE THREAD

**Issue by mjjstorey** [lemberg/connfa-integration-server#34]
For info - running bitnami lamp virtual machine, but this has happened on heroku and ubuntu fresh install too.

bitnami@debian:~/htdocs/connfa-integration-server$ php artisan migrate
Migration table created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'event_id': u
  sed in a foreign key constraint 'schedule_event_event_id_foreign' (SQL:
   alter table `schedule_event` add primary key `schedule_event_schedule_
  id_event_id_primary`(`schedule_id`, `event_id`))

  [PDOException]
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'event_id': u
  sed in a foreign key constraint 'schedule_event_event_id_foreign'

Anyone able to advise?

**Comment by vpauk** [comment]
@mjjstorey 

Thank you for the details of the problem. We are already working on a fixing this bug.

**Comment by mjjstorey** [comment]
any idea of the timescales or workaround for this?

**Comment by vpauk** [comment]
@mjjstorey 

Workaround:
You can go to folder `database/migrations` in project and change migration `CreateSchedulesEventsTable` like this:

```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSchedulesEventsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('schedule_event', function (Blueprint $table) {
            $table->integer('schedule_id')->unsigned()->nullable();
            $table->integer('event_id')->unsigned()->nullable();

            $table->primary(['schedule_id', 'event_id']);
        });

        Schema::table('schedule_event', function (Blueprint $table) {
            $table->foreign('schedule_id')->references('id')
                  ->on('schedules')->onDelete('cascade');
            $table->foreign('event_id')->references('id')
                  ->on('events')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('schedule_event');
    }
}

```
After that you should to drop tables in database and run `php artisan migrate`

**Comment by yuriymyrosh** [comment]
@mjjstorey  hi, we had released new version with bug fixing, this issue is fixed there. You can use tag 2.0.1 or fresh version of master branch
