### ISSUE TITLE
Ajax Error while adding new conference 

### ISSUE THREAD

**Issue by darshil** [lemberg/connfa-integration-server#35]
<img width="488" alt="screen shot 2018-04-08 at 1 29 05 am" src="https://user-images.githubusercontent.com/12867510/38463579-55b109d6-3acc-11e8-8a2c-e7136f73f8ab.png">

I am getting this error ^ right after logging in

Currently using Heroku to host the Integration Server. It forces HTTPS, is that the issue here and how would I fix it?

cc: @vpauk

**Comment by darshil** [comment]
<img width="976" alt="screen shot 2018-04-08 at 1 59 29 am" src="https://user-images.githubusercontent.com/12867510/38463800-8c7908a2-3ad0-11e8-9004-7bf14203b1f1.png">


This is the error I get when I try to visit the dashboard of one of the conferences.

**Comment by Daniel-HBK** [comment]
me too

**Comment by heru** [comment]
> me too

any progress with this problem ?

**Comment by yuriymyrosh** [comment]
@darshil hi, it looks like problem is with data in database not with https. Had you any problems with database migration or seeding data?

**Comment by aht61** [comment]
Did you sort this out? Earlier this was functioning properly. I have graded my server to Ubuntu 18.04 and php 7.2 this problem has occured and I cannot solve it. Could anybody help?

**Comment by yuriymyrosh** [comment]
@aht61 Hi, this is issue with count method in php7.2, currently we are not supporting php7.2

**Comment by aht61** [comment]
To which php version should I downgrade then? with many thanks.

**Comment by yuriymyrosh** [comment]
@aht61 on 5.6 it works correctly, I think that you can try also on 7.1 but we haven't tested how it works on 7.1
