### ISSUE TITLE
I have installed this package in my win server.

### ISSUE THREAD

**Issue by jin-qian-arch** [lemberg/connfa-integration-server#4]
I have installed this package in my win server.
By the way, can not see the admin panel dashboard successfully.
I got cache store does not support tagging and changed AES-256-CBC to AES-128-CBC.
So I change the file to array in cache config file.
So  I could see  the login page.
But I can not see the dashboard with time out 30s issue.
Want your help.

**Comment by yuriymyrosh** [comment]
@Jinqianv , Can you try to clear cache by running artisan command `php artisan cache:clear`. We use cache array config in our projects too and it works fine. If after cleaning cache problem still exists, please attach your log file and we will investigate them.

**Comment by yuriymyrosh** [comment]
@Jinqianv Just want to follow up on this, is the problem still relevant, or could the issue be closed? If there are any questions, just let me know.

**Comment by fadi-william** [comment]
@Konro1... I'm actually facing the same problem. However, I'm using a Mac. I was able to seed the database successfully... But, I'm not able to access the public folder... I get 'Internal Server Error'.

**Comment by fadi-william** [comment]
@Konro1... So, I'm not able to access the interface of the admin application.
