### ISSUE TITLE
Cant get Integration Server to work properly.

### ISSUE THREAD

**Issue by PatrickWV** [lemberg/connfa-integration-server#40]
Hi all together,

i am havint trouble setting up the Integration Server properly.

I followed the Installation documentation, but for someone who never developed with Laravel and/or used artisan and stuff its to simple of a documentation.

So i dir all steps that are listed in the installation documentation. After that i didnt knew how to start the server... So after some googling i was able to start a server with "php artisan serve". This server comes up on "http://localhost:8000". I am even able to log in to the CMS and create Events. But my Frontend (webapp) cant really connect to the backend, at least it is still empty. And if i try to GET "http://localhost:8000/api/v2/checkUpdates" i get a 404.

What did i do wrong?

my env:
APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:AR/0G6nVPV56DbGk0NIa1ubH2rcS4asBwMs8Rg5JMNk=
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=test
DB_PASSWORD=test

CACHE_DRIVER=array
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

API_PREFIX=api
API_DOMAIN=localhost
API_VERSION=v2
API_DEBUG=true
API_CONDITIONAL_REQUEST=false

APP_LINK_GOOGLE_PLAY=1
APP_LINK_APPLE_STORE=2

**Comment by yuriymyrosh** [comment]
@PatrickWV Hi, can you try to change API_DOMAIN in your `.env` to `http://localhost:8000`?

**Comment by PatrickWV** [comment]
Thank u.
But we've already solved the Problem. We had to leave API_DOMAIN empty in our .env file. And the Frontend doesnt need http://domain/api/v2. It needs http://domain/api/v2/eventShortcut. The Doku is a bit confusing and very basic.
