### ISSUE TITLE
login to the connfa integration server

### ISSUE THREAD

**Issue by OZGnaly** [lemberg/connfa-integration-server#7]
first all  want to thank you for the great job you've done  i was looking for an event management open source project when read the connfa docs i knew that is exactly what i'm looking for .
i fellow all the instruction to install the connfa integration server until i try this instruction  " php artisan password:change --name=admin --password=YOUR_PASSWORD_HERE" . it shows me this  "  The user is not registered." 
i try to add the user manual with phpmyadmin but it didn't work

**Comment by yuriymyrosh** [comment]
@OZGnaly this command changes password for admin user. You already need to have this user in your database. Please make sure that you have correct settings for database in your .env file and run ```php artisan migrate``` ```php artisan seed``` It will migrate your database and add admin user. After that you can change password for admin using ```php artisan password:change --name=ADMIN_USERNAME_OR_EMAIL --password=YOUR_PASSWORD_HERE```

**Comment by OZGnaly** [comment]
@Konro1  thank you for the response.

**Comment by yuriymyrosh** [comment]
@OZGnaly have this helps you to fix your problem? Let me know if i can close this issue.

**Comment by OZGnaly** [comment]
yes you can close it . thank you @Konro1

**Comment by yuriymyrosh** [comment]
You're welcome, if you have any questions/problems, just let me know
