### ISSUE TITLE
CMS not opening

### ISSUE THREAD

**Issue by bahaab** [lemberg/connfa-integration-server#9]
Dears,

I'm not able to access the admin dashboard After installing connfa integration server and pre-requisites (php, mysql, apache, composer...) as described exactly in your tutorial 
http://connfa.com/integration-server/install/

Knowing that when i access the url i can find the list of app directory.

Any help is much appreciated.

Regards

**Comment by Rfarran** [comment]
I am having the same problem.
PHP Version 5.6.29
Server API	Apache 2.0 Handler
database created and accessible from phpmyadmin
the cms itself shows directory listing :(

**Comment by matchett808** [comment]
The Directory root should be in /public, if you click on /public in the directory listing the dashboard login page should come up

**Comment by yuriymyrosh** [comment]
@bahaab, @Rfarran thank you for your questions.
@matchett808 is right. If you see list of directories it seems like your DOCUMENT_ROOT on virtual host is set as path to PROJECT_ROOT directory. It should be set as path to  PROJECT_ROOT/public directory. Please let us know if this helps you.

**Comment by bahaab** [comment]
[connfa-error-log.txt](https://github.com/lemberg/connfa-integration-server/files/716817/connfa-error-log.txt)
First I would like to thank you for your prompt answer, I changed the virtual host configuration to point directly to ../public directory 

Now i'm getting Http Error 500  when access the URL and page not found when trying URL/login or URL/dashboard

Attached you can find the Error logs.

Thank you again.

**Comment by yuriymyrosh** [comment]
@bahaab thanks for log file. You need to set write permissions to your storage folder - /var/www/html/connfa/storage. ```chmod -R 777 /var/www/html/connfa/storage/```

**Comment by bahaab** [comment]
[connfa-error-log.txt](https://github.com/lemberg/connfa-integration-server/files/716883/connfa-error-log.txt)
@Konro1  I changed the permission and restarting apache but it seems we are getting the same error (attached).

**Comment by yuriymyrosh** [comment]
Can you print ls -la in your storage dir? It should looks like this:
![image](https://cloud.githubusercontent.com/assets/3720067/22111095/c15c3638-de66-11e6-9105-4ff6544583a7.png)

**Comment by bahaab** [comment]
![storage](https://cloud.githubusercontent.com/assets/10595937/22111174/0dc9dbba-de67-11e6-925e-0774e1702911.PNG)
@Konro1 it seems that we don't have debugbar directory, not sure if this affecting the app.

**Comment by matchett808** [comment]
My local version doesn't have that directory either - to make sure the subdirectories have the same user and group Try:
   
`chown -R apache:apache /var/www/html/connfa/storage`

Also try 

`chmod -R 777 /var/www/html/connfa/`

Although the 2nd one isn't advisable for a public server

**Comment by bahaab** [comment]
Hi @matchett808   storage directory and its sub folders and files has the same ownership apache:apache and the permission provided is 777.

Regards

**Comment by matchett808** [comment]
what about storage's Parent directory?

**Comment by bahaab** [comment]
![storage](https://cloud.githubusercontent.com/assets/10595937/22113813/37172d52-de70-11e6-9eed-9988d4f41acb.PNG)
Same permissions.

**Comment by matchett808** [comment]
Storage's parent would be one more level up, (/var/www/html/connfa), it would depend on the apache settings but it might not like it

**Comment by bahaab** [comment]
granting connfa the same permissions didn't solve the problem

**Comment by yuriymyrosh** [comment]
Can you ensure that file /var/www/html/connfa/storage/logs/laravel.log realy exists? If not can you create it by yourself and give write permissions

**Comment by bahaab** [comment]
@Konro1 laravel.log file already exists with apache.apache 777 permission

**Comment by kbhatt** [comment]
i can't make storage writable in windows10. can someone help please?
Darn it was issue with my httpd.conf <Directory> tag needed additional permission which I figured out later to add. Although I found few other issues:
- The Encryption config is picking come string called SomeRandomString with wrong length and encryption type
- Register new user throws a function not found exception in validator

**Comment by yuriymyrosh** [comment]
@kbhatt for windows 10 you can give write permissions for your web server user or for all users.

To try it you can open folder property -> security tab and change there write permissions

**Comment by bahaab** [comment]
Still facing the same problem from my side. any idea?

**Comment by kbhatt** [comment]
Can you post a screenshot on how/what the error looks like? that would help. As I said your httpd.conf <Directory> tag needs additional permission at the end: **Require all granted**
if this is missing or something else it will say forbidden.
Also for the showing directory listing I guess the issue is vanila flavor apache is not understanding the directory structure in php files for autoload; i recommend using XAMP. I tried and it works well.

**Comment by bahaab** [comment]
![connfa](https://cloud.githubusercontent.com/assets/10595937/22696364/63ea9216-ed56-11e6-8867-c3de08cca237.PNG)

Thank you @kbhatt  attached you can find the 500 page error, note that Require all granted is already available.

Regards

**Comment by kbhatt** [comment]
is this on aws elb that you are getting? if yes even I'm getting this :) my guess(again) is that I havent setup the instance and ran the composer dependencies hence its not working for me.
Did you try connfa.aub.edu.lb/login instead?

**Comment by bahaab** [comment]
@kbhatt 
/login is returning (The requested URL /login was not found on this server.) we already ran the composer dependencies as per the documentation!

note that we are using a vm hosted internally and not a aws.

regards

**Comment by yuriymyrosh** [comment]
@bahaab can you show your .env file? You can clear your database connection for security

**Comment by miatribe** [comment]
@bahaab  try index.php  (I had the same problem but going to index.php took me to index.php/login)

@Konro1 I'm getting to the login but once I have loged in I get the same error but at /connfa/public/index.php/dashboard

The "IP" page isn’t working

"IP" is currently unable to handle this request.
HTTP ERROR 500

**Comment by yuriymyrosh** [comment]
@miatribe It looks like you need to turn on mod_rewrite on your web server and also you need to configure your web root to /connfa/public folder.

**Comment by miatribe** [comment]
Thanks that got it!

Might need to update the server requirements to include php-xml (composer needed it)

I also had to set CACHE_DRIVER=array due to an error when seeding the users table.

**Comment by vpauk** [comment]
In case of any questions or issues, just let us know.
